version: '3'

services:
  app:
    build: .

    image: muhammad2200/person

    container_name: person

    ports:
      - '8000:8000'

    environment:
      - NODE_ENV=production


